# Generated by Django 3.2 on 2020-11-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('test', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
        ),
    ]
