# Generated by Django 3.2 on 2020-11-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.TextField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Pending', 'Pending'), ('NA', 'NA')], default='NA'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
