# Generated by Django 3.2 on 2020-11-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectAPI', '0002_auto_20201110_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
