# Generated by Django 3.2 on 2020-11-11 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectAPI', '0005_housemate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='person_name',
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('guests', models.ManyToManyField(to='ObjectAPI.Guest')),
                ('housemate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ObjectAPI.housemate')),
                ('rooms', models.ManyToManyField(to='ObjectAPI.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('residence_id', models.AutoField(primary_key=True, serialize=False)),
                ('residence_name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=500)),
                ('housemates', models.ManyToManyField(to='ObjectAPI.Housemate')),
                ('rooms', models.ManyToManyField(to='ObjectAPI.Room')),
                ('visits', models.ManyToManyField(to='ObjectAPI.Visit')),
            ],
        ),
    ]
